const fs = require('fs');
const r = JSON.parse(fs.readFileSync('public/data/results.json', 'utf8'));

const expected = {
  "1": [
    {pos:1,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:3,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:4,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:5,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:6,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:7,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:8,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:9,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:10,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:11,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:12,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:13,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:14,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:15,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:16,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:17,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:18,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"DNF"},
    {pos:19,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"DNF"},
    {pos:20,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"DNF"},
    {pos:21,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"DNS"},
    {pos:22,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"DNS"}
  ],
  "2": [
    {pos:1,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:3,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:4,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:5,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:6,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:7,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:8,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:9,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:10,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:11,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:12,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:13,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"Finished"},
    {pos:14,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:15,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:16,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"DNF"},
    {pos:17,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"DNF"},
    {pos:18,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:19,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"DNS"},
    {pos:20,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"DNS"},
    {pos:21,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"DNS"},
    {pos:22,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"DNS"}
  ],
  "3": [
    {pos:1,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:3,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:4,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:5,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:6,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:7,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:8,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:9,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:10,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:11,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:12,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:13,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:14,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:15,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:16,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:17,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:18,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:19,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"Finished"},
    {pos:20,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:21,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:22,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"DNF"}
  ],
  "4": [
    {pos:1,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:3,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:4,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:5,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:6,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:7,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:8,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:9,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:10,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:11,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:12,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:13,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:14,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:15,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:16,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:17,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"Finished"},
    {pos:18,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"Finished"},
    {pos:19,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"DNF"},
    {pos:20,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"DNF"},
    {pos:21,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"DNF"},
    {pos:22,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"DNF"}
  ],
  "5": [
    {pos:1,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:3,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:4,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:5,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:6,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:7,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:8,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:9,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:10,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:11,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:12,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:13,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:14,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:15,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"Finished"},
    {pos:16,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"Finished"},
    {pos:17,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"DNF"},
    {pos:18,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"DNF"},
    {pos:19,driver:"George Russell",code:"RUS",team:"Mercedes",status:"DNF"},
    {pos:20,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"DNF"},
    {pos:21,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"DNF"},
    {pos:22,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"DNS"}
  ],
  "6": [
    {pos:1,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:3,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:4,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:5,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:6,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:7,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:8,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:9,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:10,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:11,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:12,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:13,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:14,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:15,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:16,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"DNF"},
    {pos:17,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"DNF"},
    {pos:18,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:19,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"DNF"},
    {pos:20,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"DNF"},
    {pos:21,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"DNF"},
    {pos:22,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"DNF"}
  ],
  "7": [
    {pos:1,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:2,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:3,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:4,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:5,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:6,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:7,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:8,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:9,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:10,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:11,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:12,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:13,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:14,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:15,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"DNF"},
    {pos:16,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"DNF"},
    {pos:17,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"DNF"},
    {pos:18,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"DNF"},
    {pos:19,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"DNF"},
    {pos:20,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"DNF"},
    {pos:21,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"DNF"},
    {pos:22,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"}
  ],
  "8": [
    {pos:1,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:3,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:4,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:5,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:6,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:7,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:8,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:9,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:10,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:11,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:12,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:13,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:14,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:15,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:16,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:17,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:18,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:19,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:20,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"DNF"},
    {pos:21,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"DNF"},
    {pos:22,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"DNF"}
  ],
  "9": [
    {pos:1,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:2,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:3,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:4,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:5,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:6,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:7,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:8,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:9,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:10,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:11,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:12,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:13,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:14,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:15,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:16,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"Finished"},
    {pos:17,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:18,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:19,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"Finished"},
    {pos:20,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"DNF"},
    {pos:21,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"DNF"},
    {pos:22,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"DNF"}
  ],
  "10": [
    {pos:1,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:3,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:4,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:5,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:6,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:7,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:8,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:9,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:10,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:11,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:12,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:13,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:14,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:15,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:16,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:17,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:18,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"Finished"},
    {pos:19,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:20,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:21,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"DNF"},
    {pos:22,driver:"George Russell",code:"RUS",team:"Mercedes",status:"DNF"}
  ],
  "11": [
    {pos:1,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:2,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:3,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:4,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:5,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:6,driver:"Isack Hadjar",code:"HAD",team:"Red Bull Racing",status:"Finished"},
    {pos:7,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:8,driver:"Liam Lawson",code:"LAW",team:"Racing Bulls",status:"Finished"},
    {pos:9,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:10,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:11,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:12,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:13,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"Finished"},
    {pos:14,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:15,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:16,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:17,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:18,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:19,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:20,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"DNF"},
    {pos:21,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"DNF"},
    {pos:22,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"DNF"}
  ],
  "12": [
    {pos:1,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:2,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:3,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:4,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:5,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:6,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:7,driver:"Liam Lawson",code:"LAW",team:"Red Bull Racing",status:"Finished"},
    {pos:8,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:9,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:10,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:11,driver:"Yuki Tsunoda",code:"TSU",team:"Racing Bulls",status:"Finished"},
    {pos:12,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:13,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:14,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:15,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:16,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:17,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"DNF"},
    {pos:18,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"DNF"},
    {pos:19,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"DNF"},
    {pos:20,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:21,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"DNF"},
    {pos:22,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"DNF"}
  ],
  "13": [
    {pos:1,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:3,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:4,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:5,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:6,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"Finished"},
    {pos:7,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:8,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:9,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:10,driver:"Yuki Tsunoda",code:"TSU",team:"Racing Bulls",status:"Finished"},
    {pos:11,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:12,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:13,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"Finished"},
    {pos:14,driver:"Liam Lawson",code:"LAW",team:"Red Bull Racing",status:"Finished"},
    {pos:15,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:16,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:17,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:18,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"Finished"},
    {pos:19,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"Finished"},
    {pos:20,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:21,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"DNF"},
    {pos:22,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"DNF"}
  ],
  "14": [
    {pos:1,driver:"Kimi Antonelli",code:"ANT",team:"Mercedes",status:"Finished"},
    {pos:2,driver:"Max Verstappen",code:"VER",team:"Red Bull Racing",status:"Finished"},
    {pos:3,driver:"Lando Norris",code:"NOR",team:"McLaren",status:"Finished"},
    {pos:4,driver:"Charles Leclerc",code:"LEC",team:"Ferrari",status:"Finished"},
    {pos:5,driver:"George Russell",code:"RUS",team:"Mercedes",status:"Finished"},
    {pos:6,driver:"Liam Lawson",code:"LAW",team:"Red Bull Racing",status:"Finished"},
    {pos:7,driver:"Franco Colapinto",code:"COL",team:"Alpine",status:"Finished"},
    {pos:8,driver:"Oscar Piastri",code:"PIA",team:"McLaren",status:"Finished"},
    {pos:9,driver:"Arvid Lindblad",code:"LIN",team:"Racing Bulls",status:"Finished"},
    {pos:10,driver:"Nico Hulkenberg",code:"HUL",team:"Audi",status:"Finished"},
    {pos:11,driver:"Esteban Ocon",code:"OCO",team:"Haas",status:"Finished"},
    {pos:12,driver:"Pierre Gasly",code:"GAS",team:"Alpine",status:"Finished"},
    {pos:13,driver:"Gabriel Bortoleto",code:"BOR",team:"Audi",status:"Finished"},
    {pos:14,driver:"Yuki Tsunoda",code:"TSU",team:"Racing Bulls",status:"Finished"},
    {pos:15,driver:"Alexander Albon",code:"ALB",team:"Williams",status:"Finished"},
    {pos:16,driver:"Oliver Bearman",code:"BEA",team:"Haas",status:"Finished"},
    {pos:17,driver:"Fernando Alonso",code:"ALO",team:"Aston Martin",status:"Finished"},
    {pos:18,driver:"Valtteri Bottas",code:"BOT",team:"Cadillac",status:"Finished"},
    {pos:19,driver:"Carlos Sainz",code:"SAI",team:"Williams",status:"DNF"},
    {pos:20,driver:"Sergio Perez",code:"PER",team:"Cadillac",status:"DNF"},
    {pos:21,driver:"Lance Stroll",code:"STR",team:"Aston Martin",status:"DNF"},
    {pos:22,driver:"Lewis Hamilton",code:"HAM",team:"Ferrari",status:"DNF"}
  ]
};

let totalErrors = 0;

for (let rnd = 1; rnd <= 14; rnd++) {
  const race = r.races[rnd.toString()];
  const exp = expected[rnd.toString()];
  let roundErrors = 0;

  for (let i = 0; i < 22; i++) {
    const a = race.results[i];
    const e = exp[i];
    const diffs = [];
    
    if (a.pos !== e.pos) diffs.push("pos");
    if (a.driver !== e.driver) diffs.push(`driver: "${a.driver}" vs "${e.driver}"`);
    if (a.code !== e.code) diffs.push(`code: "${a.code}" vs "${e.code}"`);
    if (a.team !== e.team) diffs.push(`team: "${a.team}" vs "${e.team}"`);
    if (a.status !== e.status) diffs.push(`status: "${a.status}" vs "${e.status}"`);
    
    if (diffs.length > 0) {
      roundErrors++;
      console.log(`R${rnd} pos ${e.pos}: ${diffs.join(" | ")}`);
    }
  }
  
  if (roundErrors === 0) {
    console.log(`R${rnd}: OK`);
  }
  totalErrors += roundErrors;
}

console.log(`\nTotal errors: ${totalErrors}`);
